(function(T){
  'use strict';
  const root=document.getElementById('app');let config=T.Config.load(),controller,graph;
  const money=n=>Math.round(n).toLocaleString('sv-SE')+' kr';
  const percent=(n,d=1)=>(n*100).toLocaleString('sv-SE',{minimumFractionDigits:d,maximumFractionDigits:d})+' %';
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function base(content){return `<main class="shell"><div class="brand"><b>TIME IN THE MARKET</b><span class="eyebrow">20 år · 240 månader</span></div>${content}</main>`;}
  function field(key,label,scale=1,suffix=''){const value=Number((config[key]*scale).toFixed(12));return `<div class="field"><label for="${key}">${label}</label><div><input id="${key}" name="${key}" type="number" step="0.01" value="${value}">${suffix}</div></div>`;}
  function renderAdmin(){
    const tests=T.Tests.run(config);root.innerHTML=base(`<span class="eyebrow">Administratör</span><h2>Spelinställningar</h2><p class="lede">Värdena sparas lokalt i den här webbläsaren och används i kommande spel.</p><form id="settings" class="settings card">${field('startingCapital','Startkapital',1,' kr')}${field('annualMarketReturn','Årlig marknadsavkastning',100,' %')}${field('annualFixedReturn','Årlig ränta',100,' %')}${field('insuranceFee','Försäkringsavgift',100,' %')}${field('newInsuranceFee','Ny försäkringsavgift',100,' %')}${field('normalFundFee','Aktiefondsavgift',100,' %')}${field('leveragedFundFee','Hävstångsfondsavgift',100,' %')}${field('leverageMultiplier','Hävstång',1,' ×')}${field('pensionTax','Schablonskatt',100,' %')}${field('gameDurationSeconds','Aktiv speltid',1,' sek')}</form><div class="actions"><button class="button primary big" id="continue">Fortsätt till spelet</button><button class="button ghost" id="reset">Återställ standardvärden</button></div><p class="small ${tests.pass?'test-ok':'test-bad'}">Inbyggd validering: ${tests.pass?'alla '+tests.results.length+' tester godkända':'fel i '+tests.results.filter(x=>!x.pass).map(x=>x.name).join(', ')}</p>`);
    document.getElementById('continue').onclick=()=>{const form=new FormData(document.getElementById('settings'));const scales={annualMarketReturn:100,annualFixedReturn:100,insuranceFee:100,newInsuranceFee:100,normalFundFee:100,leveragedFundFee:100,pensionTax:100};for(const [k,v] of form){const n=Number(v);if(Number.isFinite(n))config[k]=n/(scales[k]||1);}config.months=config.years*12;T.Config.save(config);controller=new T.GameController(config,render);try{controller.prepare();}catch(e){root.insertAdjacentHTML('beforeend',`<p class="error">${esc(e.message)}</p>`);}};
    document.getElementById('reset').onclick=()=>{config=T.Config.reset();renderAdmin();};
  }
  function renderStart(s){root.innerHTML=base(`<span class="eyebrow">Ditt beslut börjar nu</span><h1>Tid på marknaden slår tajming av marknaden.</h1><p class="lede">Du har ${money(config.startingCapital)} och ${config.years} år framför dig. Välj hur mycket du vill placera på börsen. Resten får ${percent(config.annualFixedReturn)} ränta. Under spelet kan du pausa och ändra fördelningen. Målet är att slå den som investerar allt på börsen från början och inte gör någonting.</p><div class="start-grid"><section class="card graph-card"><span class="eyebrow">De senaste fem åren</span><canvas id="graph"></canvas></section><section class="card"><h3>Din startfördelning</h3><div class="choice-row" id="initial">${[0,.25,.5,.75,1].map(v=>`<button class="button ${v===1?'primary':'ghost'}" data-share="${v}">${v*100} % börs</button>`).join('')}</div><div class="assumptions"><div class="assumption"><span>Försäkringsavgift</span><b>${percent(config.insuranceFee,2)}</b></div><div class="assumption"><span>Fondavgift</span><b>${percent(config.normalFundFee,2)}</b></div><div class="assumption"><span>Ränta</span><b>${percent(config.annualFixedReturn,2)}</b></div><div class="assumption"><span>Schablonskatt</span><b>${percent(config.pensionTax,2)}</b></div></div><button id="back" class="button ghost">Inställningar</button></section></div>`);graph=new T.MarketGraph(document.getElementById('graph'));graph.draw(s);document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>controller.start(Number(b.dataset.share)));document.getElementById('back').onclick=()=>renderAdmin();}
  function renderGame(s){const p=s.portfolio,b=s.buyHold,a=T.Finance.allocations(p),diff=T.Finance.total(p)-T.Finance.total(b),remaining=Math.max(0,1-s.activeElapsed/config.gameDurationSeconds);root.innerHTML=`<main class="shell game-shell"><div class="brand"><b>TIME IN THE MARKET</b><span class="eyebrow">Månad ${s.currentMonth} av ${config.months}</span></div><div class="game-top"><div class="card metric"><span class="eyebrow">Buy & Hold</span><strong>${money(T.Finance.total(b))}</strong></div><div class="card metric player"><span class="eyebrow">Din portfölj</span><strong>${money(T.Finance.total(p))}</strong><span class="diff ${diff>=0?'positive':'negative'}">${diff>=0?'+':''}${money(diff)} mot Buy & Hold</span></div><div class="present-line"></div></div><div class="game-stage"><section class="market-panel"><canvas id="graph"></canvas></section><aside class="side-panel"><div class="eyebrow">Aktuell tid</div><div class="year">År ${Math.min(config.years,Math.floor(s.currentMonth/12)+1)}</div><div class="allocation">Börs ${percent(a.equity,0)} · Ränta ${percent(a.fixed,0)}${p.lockedLeveraged>0?` · Låst hävstång ${percent(a.leveraged,0)}`:''}</div><div class="timer"><i style="width:${remaining*100}%"></i></div><div class="actions"><button id="pause" class="button warn big">${s.pendingManual?'PAUSAR VID MÅNADSSLUT…':'PAUSA & ÄNDRA'}</button></div>${config.debug?`<pre class="debug">${esc(JSON.stringify({month:s.currentMonth,marketReturn:s.marketPath[s.currentMonth-1],marketIndex:s.marketIndexes[s.currentMonth],portfolio:p,allocation:a,buyHold:T.Finance.total(b),pendingEvent:s.pendingEvent&&s.pendingEvent.id,decisionLog:s.decisionLog},null,2))}</pre>`:''}<div class="abort-row"><button id="abort" class="button ghost">AVBRYT</button></div></aside></div></main>`;graph=new T.MarketGraph(document.getElementById('graph'));graph.draw(s);}
  function renderDecision(s,type){const isEvent=type==='event',e=s.pendingEvent;root.innerHTML=base(`<section class="card decision"><span class="eyebrow">Spelet är pausat · Månad ${s.currentMonth}</span><h2>${isEvent?esc(e.title):'Ändra din fördelning'}</h2><p class="lede">${isEvent?esc(e.description(config,s.portfolio)):`Välj hur det tillgängliga kapitalet ska fördelas. ${s.portfolio.lockedLeveraged>0?'Den låsta hävstångsdelen påverkas inte.':''}`}</p>${!isEvent&&s.portfolio.lockedLeveraged>0?'<div class="locked-note">Valet gäller endast Börs och Ränta i den olåsta delen.</div>':''}<div class="choice-row">${isEvent?'<button class="button primary big" data-answer="yes">JA</button><button class="button ghost big" data-answer="no">NEJ</button>':[0,.25,.5,.75,1].map(v=>`<button class="button ${v===.5?'primary':'ghost'}" data-share="${v}">${v*100} % börs</button>`).join('')}</div><div class="abort-row"><button id="abort" class="button ghost">AVBRYT</button></div></section>`);if(isEvent)document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>controller.chooseEvent(b.dataset.answer==='yes'));else document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>controller.chooseManual(Number(b.dataset.share)));}
  function renderResult(s){const r=s.results,d=r.actual.finalValue-r.buy.finalValue,dp=d/r.buy.finalValue,p=r.actual.portfolio,e=r.effects;const effectRow=(label,x)=>`<div class="detail-row"><span>${label}</span><b class="${x>=0?'positive':'negative'}">${x>=0?'+':''}${money(x)}</b></div>`;root.innerHTML=base(`<span class="eyebrow">Dina 20 år är slut</span><div class="result-grid"><section class="card hero-result"><div class="eyebrow">Ditt slutkapital</div><div class="amount">${money(r.actual.finalValue)}</div><div class="comparison"><b>Buy & Hold ${money(r.buy.finalValue)}</b><p class="${d>=0?'positive':'negative'}">${d>=0?'+':''}${money(d)} · ${d>=0?'+':''}${percent(dp)} mot Buy & Hold</p></div><div class="actions"><button id="again" class="button primary big">SPELA IGEN</button></div><div class="abort-row"><button id="abort" class="button ghost">AVBRYT</button></div></section><section class="card"><h3>Vad påverkade resultatet?</h3>${effectRow('Dina egna omviktningar',e.manual.effect)}${effectRow('Flytt år 2',e.transfer.effect)}${effectRow('Hävstång år 5',e.leverage.effect)}${effectRow('Räntebeslut år 10',e.fixed.effect)}${effectRow('Riskminskning år 17',e.reduce.effect)}<p class="small">Effekterna beräknas var för sig genom att simulera samma marknad utan det aktuella beslutet. Eftersom dina beslut påverkar varandra summerar de inte alltid exakt till skillnaden mot Buy & Hold.</p></section></div><section class="card" style="margin-top:24px"><h3>Avgifter och skatt</h3><div class="details"><div class="detail-row"><span>Normal fondavgift</span><b>${money(p.cumulativeNormalFundFees)}</b></div><div class="detail-row"><span>Hävstångsfondens avgift</span><b>${money(p.cumulativeLeveragedFundFees)}</b></div><div class="detail-row"><span>Försäkringsavgift</span><b>${money(p.cumulativeInsuranceFees)}</b></div><div class="detail-row"><span>Beräknad besparing i försäkringsavgift</span><b>${money(e.insuranceSavings)}</b></div><div class="detail-row"><span>Schablonskatt</span><b>${money(p.cumulativeTax)}</b></div></div></section>`);document.getElementById('again').onclick=()=>controller.prepare();}
  function render(s){if(!s)return;if(s.currentScreen==='start')renderStart(s);else if(s.currentScreen==='game')renderGame(s);else if(s.currentScreen==='manual')renderDecision(s,'manual');else if(s.currentScreen==='event')renderDecision(s,'event');else if(s.currentScreen==='result')renderResult(s);}
  root.addEventListener('pointerdown',event=>{if(event.target.closest('#pause'))controller.requestManual();});
  root.addEventListener('pointerdown',event=>{if(event.target.closest('#abort'))controller.abort();});
  window.addEventListener('keydown',event=>{const target=event.target,inControl=target instanceof Element&&target.matches('input, textarea, select, button, [contenteditable="true"]');if(event.code!=='Space'||event.repeat||inControl||!controller||controller.state.currentScreen!=='game'||!controller.state.running)return;event.preventDefault();controller.requestManual();});
  window.addEventListener('resize',()=>{if(graph&&controller)graph.draw(controller.state);});window.TimeMarket.debugMarket=count=>T.Market.debugMany(config,count);window.TimeMarket.runTests=()=>T.Tests.run(config);renderAdmin();
})(window.TimeMarket);
